# LAB 2 WORKING WITH ARRAYS USING JUPYTER

# Q1. convert the below list into numpy array and displaying

In [1]:
import numpy as np 

In [2]:
my_list=[1,2,3,4]
arr=np.array(my_list)

In [3]:
print(my_list)

[1, 2, 3, 4]


# Q2. convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result

In [4]:
list=[2,3,5,6,8,9]

In [5]:
ar=np.array(list)
print(ar)

[2 3 5 6 8 9]


In [8]:
print(ar[0])
print(ar[-1])

2
9


In [9]:
print(ar*2)

[ 4  6 10 12 16 18]


# Q3. write a numpy program to create an array of 10 zeros,10 ones,10 fives

In [11]:
arr=np.zeros((10),dtype="int")
print("array of zeros:" ,arr)

array of zeros: [0 0 0 0 0 0 0 0 0 0]


In [12]:
arr=np.ones((10),dtype="int")
print("array of ones:" ,arr)

array of ones: [1 1 1 1 1 1 1 1 1 1]


In [15]:
arr=np.ones((10),dtype="int")
print("array of 10 fives:",arr*5)

array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


# Q4. write a numpy program to create a 3*3 matrix with values ranging from 2 to 10

In [18]:
ar=np.arange(2,11)
print(ar)
ar=ar.reshape(3,3)
print(ar)


[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
