# LAB 4 

# Q1. calculate total revenue generated by 2 product categories in a store

In [3]:
import numpy as np 

In [5]:
category1_revenue = np.array([500,600,700,550])
category2_revenue = np.array([450,700,800,600])
total_revenue=category1_revenue+category2_revenue
print(total_revenue)

[ 950 1300 1500 1150]


# Q2. calculate profit made by company 

In [6]:
revenue=np.array([10000,12000,11000,10500])
expenses=np.array([4000,5000,4500,4800])
print(revenue)
print(expenses)
profit=revenue-expenses
print(profit)

[10000 12000 11000 10500]
[4000 5000 4500 4800]
[6000 7000 6500 5700]


# Q3. determine which product in a store are out of stock(quantity is 0)

In [12]:
inventory=np.array([10,0,5,0,20,0])
print("out of stock")
print(inventory[inventory==0])    

out of stock
[0 0 0]


# Q4. calculate the total cost of item in a shopping cart,considering the quantity and price per item 

In [13]:
quantity=np.array([2,3,4,1])
price = np.array([10.0,5.0,8.0,12.0])
print(quantity*price)

[20. 15. 32. 12.]
